type: google.api.Service
config_version: 3

#
# Name of the Service Configuration.
#
name: grpc.endpoints.PROJECT_ID.cloud.goog
endpoints:
  - name: grpc.endpoints.PROJECT_ID.cloud.goog
    target: "<EXTERNAL_IP_ADDRESS>"

title: Test gRPC API
apis:
  - name: PublicAccessService
  - name: SecuredAccessService

usage:
  rules:
    - selector: "*"
      allow_unregistered_calls: true