apiVersion: v1
kind: Service
metadata:
  name: grpc-test-server
spec:
  type: LoadBalancer
  ports:
  # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
  - port: 9000
    targetPort: 9000
    name: esp-grpc
  selector:
    deploy: grpc-test-server