apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-test-server
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: grpc-test-server
  template:
    metadata:
      labels:
        deploy: grpc-test-server
    spec:
      containers:
        - name: grpc-test-server
          image: sarora139/grpc-test-server:latest
          ports:
            - containerPort: 9090
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http_port=8080",
            "--http2_port=9000",
            "--service=grpc.endpoints.nodejs-238515.cloud.goog",
            "--rollout_strategy=managed",
            "--backend=grpc://127.0.0.1:9090"
          ]
          ports:
            - containerPort: 9000
            - containerPort: 8080