apiVersion: v1
kind: Service
metadata:
  name: grpc-test-server
spec:
  type: LoadBalancer
  ports:
    # Port that accepts JSON/HTTP1.1 requests over HTTP.
    - port: 8080
      targetPort: 8080
      name: http
    # Port that accepts https requests
    - port: 443
      name: https
  selector:
    deploy: grpc-test-server